version: "3.9"
services:
  app:
    container_name: ai-chat-bot-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
    stdin_open: true
